//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerManagerSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysRole
    {
        public SysRole()
        {
            this.SysRoleModuleOperations = new HashSet<SysRoleModuleOperations>();
            this.SysUserRole = new HashSet<SysUserRole>();
        }
    
        public int Id { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> Creator { get; set; }
    
        public virtual ICollection<SysRoleModuleOperations> SysRoleModuleOperations { get; set; }
        public virtual ICollection<SysUserRole> SysUserRole { get; set; }
    }
}
