//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerManagerSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUserOperateLog
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserIp { get; set; }
        public string OperateInfo { get; set; }
        public string Description { get; set; }
        public bool IfSuccess { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
    
        public virtual SysUser SysUser { get; set; }
    }
}
